// Auto-generate products from public folder images
// This script creates products in Sanity using images from the public folder

export interface PublicFolderProduct {
  name: string;
  slug: string;
  description: string;
  price: number;
  originalPrice: number;
  publicImagePath: string;
  category: string;
  stock: number;
  featured: boolean;
  rating: number;
  reviewCount: number;
}

// List of image files from public folder to create as products
// You can customize this list or auto-generate it
export const publicFolderProducts: PublicFolderProduct[] = [
  {
    name: 'Premium Laptop Pro',
    slug: 'premium-laptop-pro',
    description: 'High-performance laptop with stunning display and powerful processor. Perfect for professionals and creators.',
    price: 89999,
    originalPrice: 120000,
    publicImagePath: '/laptop1.png',
    category: 'electronics',
    stock: 25,
    featured: true,
    rating: 4.8,
    reviewCount: 342,
  },
  {
    name: 'UltraBook Air',
    slug: 'ultrabook-air',
    description: 'Lightweight and powerful ultrabook with all-day battery life. Perfect for students and professionals on the go.',
    price: 75999,
    originalPrice: 95000,
    publicImagePath: '/laptop2.png',
    category: 'electronics',
    stock: 30,
    featured: true,
    rating: 4.7,
    reviewCount: 256,
  },
  {
    name: 'Gaming Laptop X',
    slug: 'gaming-laptop-x',
    description: 'Ultimate gaming laptop with RTX graphics and high refresh rate display. Dominate every game.',
    price: 125999,
    originalPrice: 160000,
    publicImagePath: '/laptop3.jpg',
    category: 'electronics',
    stock: 15,
    featured: true,
    rating: 4.9,
    reviewCount: 189,
  },
  {
    name: 'Business Laptop Elite',
    slug: 'business-laptop-elite',
    description: 'Professional laptop with enterprise-grade security and performance. Built for business.',
    price: 95999,
    originalPrice: 130000,
    publicImagePath: '/laptop4.png',
    category: 'electronics',
    stock: 20,
    featured: true,
    rating: 4.6,
    reviewCount: 178,
  },
  {
    name: 'Classic Denim Jacket',
    slug: 'classic-denim-jacket',
    description: 'Timeless denim jacket with modern fit. Perfect for any casual occasion.',
    price: 3499,
    originalPrice: 4999,
    publicImagePath: '/pic.jpg',
    category: 'clothing',
    stock: 50,
    featured: true,
    rating: 4.5,
    reviewCount: 234,
  },
  {
    name: 'Urban Style Jacket',
    slug: 'urban-style-jacket',
    description: 'Contemporary jacket with urban aesthetics. Stay warm and stylish.',
    price: 4299,
    originalPrice: 5999,
    publicImagePath: '/pic1.jpg',
    category: 'clothing',
    stock: 40,
    featured: false,
    rating: 4.4,
    reviewCount: 156,
  },
  {
    name: 'Winter Parka',
    slug: 'winter-parka',
    description: 'Warm and comfortable winter parka. Perfect for cold weather.',
    price: 5999,
    originalPrice: 8999,
    publicImagePath: '/pic2.jpg',
    category: 'clothing',
    stock: 35,
    featured: true,
    rating: 4.7,
    reviewCount: 198,
  },
  {
    name: 'Casual Hoodie',
    slug: 'casual-hoodie',
    description: 'Comfortable cotton hoodie for everyday wear. Soft and cozy.',
    price: 2499,
    originalPrice: 3499,
    publicImagePath: '/pic3.jpg',
    category: 'clothing',
    stock: 60,
    featured: false,
    rating: 4.3,
    reviewCount: 287,
  },
  {
    name: 'Summer Breeze Shirt',
    slug: 'summer-breeze-shirt',
    description: 'Light and breathable shirt perfect for summer days.',
    price: 1999,
    originalPrice: 2999,
    publicImagePath: '/pic4.jpg',
    category: 'clothing',
    stock: 75,
    featured: false,
    rating: 4.2,
    reviewCount: 145,
  },
  {
    name: 'Elegant Evening Dress',
    slug: 'elegant-evening-dress',
    description: 'Stunning evening dress for special occasions. Look your best.',
    price: 6999,
    originalPrice: 9999,
    publicImagePath: '/pic5.jpg',
    category: 'clothing',
    stock: 25,
    featured: true,
    rating: 4.8,
    reviewCount: 167,
  },
  {
    name: 'Casual Friday Wear',
    slug: 'casual-friday-wear',
    description: 'Perfect outfit for casual Fridays at the office.',
    price: 3299,
    originalPrice: 4599,
    publicImagePath: '/pic6.jpg',
    category: 'clothing',
    stock: 45,
    featured: false,
    rating: 4.4,
    reviewCount: 123,
  },
  {
    name: 'Weekender Outfit',
    slug: 'weekender-outfit',
    description: 'Comfortable and stylish outfit for weekend adventures.',
    price: 2799,
    originalPrice: 3999,
    publicImagePath: '/pic7.jpg',
    category: 'clothing',
    stock: 55,
    featured: false,
    rating: 4.3,
    reviewCount: 98,
  },
  {
    name: 'Abstract Art Print',
    slug: 'abstract-art-print',
    description: 'Beautiful abstract art print for your home or office.',
    price: 1499,
    originalPrice: 2499,
    publicImagePath: '/new.jpg',
    category: 'home',
    stock: 100,
    featured: false,
    rating: 4.5,
    reviewCount: 87,
  },
  {
    name: 'Modern Wall Decor',
    slug: 'modern-wall-decor',
    description: 'Contemporary wall decor to enhance your living space.',
    price: 1999,
    originalPrice: 2999,
    publicImagePath: '/new1.jpg',
    category: 'home',
    stock: 80,
    featured: false,
    rating: 4.4,
    reviewCount: 76,
  },
  {
    name: 'Vintage Poster',
    slug: 'vintage-poster',
    description: 'Classic vintage poster reproduction. Add a touch of nostalgia.',
    price: 899,
    originalPrice: 1499,
    publicImagePath: '/new2.jpg',
    category: 'home',
    stock: 120,
    featured: false,
    rating: 4.2,
    reviewCount: 54,
  },
  {
    name: 'Minimalist Art',
    slug: 'minimalist-art',
    description: 'Clean and minimalist art piece for modern interiors.',
    price: 1799,
    originalPrice: 2599,
    publicImagePath: '/new3.jpg',
    category: 'home',
    stock: 90,
    featured: false,
    rating: 4.6,
    reviewCount: 112,
  },
]

// Helper function to generate product document for Sanity
export const createProductDocument = (product: PublicFolderProduct) => {
  return {
    _type: 'product' as const,
    name: product.name,
    slug: {
      _type: 'slug' as const,
      current: product.slug,
    },
    description: product.description,
    price: product.price,
    originalPrice: product.originalPrice,
    publicImagePath: product.publicImagePath,
    category: product.category,
    stock: product.stock,
    featured: product.featured,
    rating: product.rating,
    reviewCount: product.reviewCount,
  }
}
