// Products data with public folder images
export const products = [
  {
    name: 'Premium Laptop Pro',
    slug: 'premium-laptop-pro',
    description: 'High-performance laptop with latest processor, 16GB RAM, and 512GB SSD. Perfect for professionals and gamers.',
    price: 89999,
    originalPrice: 109999,
    publicImagePath: '/laptop1.png',
    category: 'electronics',
    stock: 50,
    featured: true,
    rating: 4.8,
    reviewCount: 245,
  },
  {
    name: 'UltraBook Slim',
    slug: 'ultrabook-slim',
    description: 'Lightweight and powerful ultrabook with 14-hour battery life. Ideal for students and business travelers.',
    price: 64999,
    originalPrice: 74999,
    publicImagePath: '/laptop2.png',
    category: 'electronics',
    stock: 35,
    featured: true,
    rating: 4.6,
    reviewCount: 189,
  },
  {
    name: 'Gaming Beast Laptop',
    slug: 'gaming-beast-laptop',
    description: 'Ultimate gaming laptop with RTX graphics, 32GB RAM, and 1TB SSD. Experience gaming like never before.',
    price: 149999,
    originalPrice: 179999,
    publicImagePath: '/laptop3.jpg',
    category: 'electronics',
    stock: 20,
    featured: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    name: 'Business Laptop',
    slug: 'business-laptop',
    description: 'Reliable business laptop with excellent keyboard and long battery life. Perfect for productivity.',
    price: 54999,
    originalPrice: 64999,
    publicImagePath: '/laptop4.png',
    category: 'electronics',
    stock: 45,
    featured: false,
    rating: 4.5,
    reviewCount: 156,
  },
  {
    name: 'Stylish Blue Watch',
    slug: 'stylish-blue-watch',
    description: 'Elegant blue wristwatch with premium build quality. Perfect accessory for formal occasions.',
    price: 4999,
    originalPrice: 7999,
    publicImagePath: '/blue.png',
    category: 'clothing',
    stock: 100,
    featured: true,
    rating: 4.3,
    reviewCount: 89,
  },
  {
    name: 'Classic Blue Watch Premium',
    slug: 'classic-blue-watch-premium',
    description: 'Premium edition blue watch with sapphire crystal and leather strap.',
    price: 8999,
    originalPrice: 12999,
    publicImagePath: '/blue.jpg.png',
    category: 'clothing',
    stock: 75,
    featured: true,
    rating: 4.7,
    reviewCount: 134,
  },
  {
    name: 'Designer Handbag',
    slug: 'designer-handbag',
    description: 'Luxury designer handbag made from premium leather. Spacious and stylish.',
    price: 12999,
    originalPrice: 18999,
    publicImagePath: '/pic.jpg',
    category: 'clothing',
    stock: 40,
    featured: true,
    rating: 4.6,
    reviewCount: 201,
  },
  {
    name: 'Elegant Purse',
    slug: 'elegant-purse',
    description: 'Compact and elegant purse perfect for evening outings and parties.',
    price: 3499,
    originalPrice: 4999,
    publicImagePath: '/pic1.jpg',
    category: 'clothing',
    stock: 60,
    featured: false,
    rating: 4.4,
    reviewCount: 78,
  },
  {
    name: 'Premium Leather Bag',
    slug: 'premium-leather-bag',
    description: 'Handcrafted premium leather bag with multiple compartments for organization.',
    price: 8999,
    originalPrice: 11999,
    publicImagePath: '/pic2.jpg',
    category: 'clothing',
    stock: 55,
    featured: true,
    rating: 4.5,
    reviewCount: 167,
  },
  {
    name: 'Classic Tote Bag',
    slug: 'classic-tote-bag',
    description: 'Versatile tote bag for daily use. Spacious interior with durable construction.',
    price: 2999,
    originalPrice: 3999,
    publicImagePath: '/pic3.jpg',
    category: 'clothing',
    stock: 80,
    featured: false,
    rating: 4.2,
    reviewCount: 92,
  },
  {
    name: 'Vintage Style Bag',
    slug: 'vintage-style-bag',
    description: 'Retro-inspired bag with modern functionality. Perfect for vintage lovers.',
    price: 5499,
    originalPrice: 7499,
    publicImagePath: '/pic4.jpg',
    category: 'clothing',
    stock: 45,
    featured: false,
    rating: 4.3,
    reviewCount: 65,
  },
  {
    name: 'Designer Clutch',
    slug: 'designer-clutch',
    description: 'Elegant designer clutch for special occasions. Compact yet spacious.',
    price: 4499,
    originalPrice: 5999,
    publicImagePath: '/pic5.jpg',
    category: 'clothing',
    stock: 50,
    featured: true,
    rating: 4.6,
    reviewCount: 112,
  },
  {
    name: 'Casual Backpack',
    slug: 'casual-backpack',
    description: 'Comfortable casual backpack for daily commute and weekend trips.',
    price: 3999,
    originalPrice: 5499,
    publicImagePath: '/pic6.jpg',
    category: 'clothing',
    stock: 70,
    featured: false,
    rating: 4.4,
    reviewCount: 145,
  },
  {
    name: 'Luxury Evening Bag',
    slug: 'luxury-evening-bag',
    description: 'Glamorous evening bag with metallic finish. Perfect for parties.',
    price: 6999,
    originalPrice: 9999,
    publicImagePath: '/pic7.jpg',
    category: 'clothing',
    stock: 35,
    featured: true,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    name: 'Modern Car Accessory',
    slug: 'modern-car-accessory',
    description: 'Premium car accessory for modern vehicles. Enhances comfort and style.',
    price: 2499,
    originalPrice: 3499,
    publicImagePath: '/car.jpg',
    category: 'other',
    stock: 90,
    featured: false,
    rating: 4.1,
    reviewCount: 56,
  },
  {
    name: 'Couple Gift Set',
    slug: 'couple-gift-set',
    description: 'Special gift set for couples. Perfect for anniversaries and special occasions.',
    price: 4999,
    originalPrice: 6999,
    publicImagePath: '/couple.jpg',
    category: 'other',
    stock: 65,
    featured: true,
    rating: 4.8,
    reviewCount: 234,
  },
  {
    name: 'Premium Headphones',
    slug: 'premium-headphones',
    description: 'Noise-cancelling premium headphones with exceptional sound quality.',
    price: 14999,
    originalPrice: 19999,
    publicImagePath: '/new.jpg',
    category: 'electronics',
    stock: 40,
    featured: true,
    rating: 4.7,
    reviewCount: 289,
  },
  {
    name: 'Wireless Earbuds Pro',
    slug: 'wireless-earbuds-pro',
    description: 'True wireless earbuds with active noise cancellation and long battery life.',
    price: 8999,
    originalPrice: 12999,
    publicImagePath: '/new1.jpg',
    category: 'electronics',
    stock: 85,
    featured: true,
    rating: 4.5,
    reviewCount: 412,
  },
  {
    name: 'Smart Speaker',
    slug: 'smart-speaker',
    description: 'Voice-controlled smart speaker with premium audio quality.',
    price: 6999,
    originalPrice: 9999,
    publicImagePath: '/new2.jpg',
    category: 'electronics',
    stock: 60,
    featured: false,
    rating: 4.4,
    reviewCount: 178,
  },
  {
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: 'Compact portable speaker with powerful bass and waterproof design.',
    price: 3499,
    originalPrice: 4999,
    publicImagePath: '/new3.jpg',
    category: 'electronics',
    stock: 95,
    featured: true,
    rating: 4.3,
    reviewCount: 267,
  },
  {
    name: 'Home Decor Set',
    slug: 'home-decor-set',
    description: 'Beautiful home decor set to enhance your living space aesthetics.',
    price: 5999,
    originalPrice: 8999,
    publicImagePath: '/last.jpg.png',
    category: 'home',
    stock: 50,
    featured: false,
    rating: 4.5,
    reviewCount: 134,
  },
  {
    name: 'Premium Home Accents',
    slug: 'premium-home-accents',
    description: 'Luxury home accents for sophisticated interior design.',
    price: 9999,
    originalPrice: 14999,
    publicImagePath: '/last2.jpg',
    category: 'home',
    stock: 30,
    featured: true,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    name: 'Modern Living Set',
    slug: 'modern-living-set',
    description: 'Contemporary living set for modern homes. Elegant and functional.',
    price: 7499,
    originalPrice: 10999,
    publicImagePath: '/last3.jpg',
    category: 'home',
    stock: 40,
    featured: false,
    rating: 4.4,
    reviewCount: 87,
  },
  {
    name: 'Sports Fitness Tracker',
    slug: 'sports-fitness-tracker',
    description: 'Advanced fitness tracker with heart rate monitoring and GPS.',
    price: 4999,
    originalPrice: 7999,
    publicImagePath: '/product-cover-5 (10).png',
    category: 'sports',
    stock: 75,
    featured: true,
    rating: 4.5,
    reviewCount: 345,
  },
  {
    name: 'Running Shoes Pro',
    slug: 'running-shoes-pro',
    description: 'Professional running shoes with advanced cushioning technology.',
    price: 6999,
    originalPrice: 9999,
    publicImagePath: '/product-cover-5 (11).png',
    category: 'sports',
    stock: 60,
    featured: true,
    rating: 4.7,
    reviewCount: 421,
  },
  {
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra thick premium yoga mat with non-slip surface.',
    price: 1999,
    originalPrice: 2999,
    publicImagePath: '/product-cover-5 (12).png',
    category: 'sports',
    stock: 100,
    featured: false,
    rating: 4.3,
    reviewCount: 189,
  },
  {
    name: 'Dumbbells Set',
    slug: 'dumbbells-set',
    description: 'Adjustable dumbbells set for home workouts. Multiple weight options.',
    price: 8999,
    originalPrice: 12999,
    publicImagePath: '/product-cover-5 (13).png',
    category: 'sports',
    stock: 45,
    featured: true,
    rating: 4.6,
    reviewCount: 267,
  },
  {
    name: 'Resistance Bands Kit',
    slug: 'resistance-bands-kit',
    description: 'Complete resistance bands kit for full-body workouts at home.',
    price: 1499,
    originalPrice: 2499,
    publicImagePath: '/product-cover-5 (14).png',
    category: 'sports',
    stock: 120,
    featured: false,
    rating: 4.4,
    reviewCount: 312,
  },
  {
    name: 'Jump Rope Speed',
    slug: 'jump-rope-speed',
    description: 'Professional speed jump rope for cardio and fitness training.',
    price: 599,
    originalPrice: 999,
    publicImagePath: '/product-cover-5 (15).png',
    category: 'sports',
    stock: 150,
    featured: false,
    rating: 4.2,
    reviewCount: 156,
  },
  {
    name: 'Gym Bag Pro',
    slug: 'gym-bag-pro',
    description: 'Spacious gym bag with shoe compartment and water bottle holder.',
    price: 2999,
    originalPrice: 3999,
    publicImagePath: '/product-cover-5 (16).png',
    category: 'sports',
    stock: 80,
    featured: true,
    rating: 4.5,
    reviewCount: 198,
  },
  {
    name: 'Sports Water Bottle',
    slug: 'sports-water-bottle',
    description: 'Insulated sports water bottle keeps drinks cold for 24 hours.',
    price: 899,
    originalPrice: 1299,
    publicImagePath: '/product-cover-5 (17).png',
    category: 'sports',
    stock: 200,
    featured: false,
    rating: 4.3,
    reviewCount: 445,
  },
]
